name: Go
on:
  push:
    tags:
      - v*
    branches:
      - master
      - main
  pull_request:
jobs:
  golangci:
    name: Review
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Generate migration files
        uses: cedrickring/golang-action@1.7.0
        with:
          args: go get github.com/rakyll/statik && make gen
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        env:
          GO111MODULE: "on"
        with:
          version: v1.41
          args: --enable=gosec --timeout=5m
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: test
        uses: cedrickring/golang-action@1.7.0
        env:
          GO111MODULE: "on"
        with:
          args: go get github.com/rakyll/statik && make gen && go test -coverprofile=coverage.out ./...
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.out
          name: codecov-umbrella
          fail_ci_if_error: true
  buildable:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: build
        uses: cedrickring/golang-action@1.7.0
        env:
          GO111MODULE: "on"
        with:
          args: go get github.com/rakyll/statik && make gen && go build ./...
